#
name: "CI/CD Deployment"

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: dev-app-repo
  TF_CLOUD_ORGANIZATION: "DigitalTech"
  TF_WORKSPACE: "gitaction_aws_container"
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_COLOR: '#36a64f'
  SLACK_MESSAGE: "Deployment started for commit: ${{ github.sha }}"
  SLACK_TITLE: "Deployment Status: STARTING"
jobs:
  # JOB 1: Ensure ECR exists via Terraform
  terraform-base:
    name: "Provision Infrastructure"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      # - name: Terraform plan (Base)
      #   # Ensures ECR is created before Docker tries to push to it
      #   run: terraform plan
     
      - name: Terraform Apply (Base)
        # Ensures ECR is created before Docker tries to push to it
        run: terraform apply -auto-approve

        # --- SUCCESS NOTIFICATION ---
      - name: Slack Notification - Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: 'good'
          SLACK_MESSAGE: "✅ ECR created SUCCESSFUL!"
          SLACK_TITLE: "ECR creation Status: SUCCESS"

      # --- FAILURE NOTIFICATION ---
      - name: Slack Notification - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: "❌ ECR FAILED. Check GitHub Actions logs."
          SLACK_TITLE: "ECR creation Status: FAILED"

  # JOB 2: Build Image and Update ECS
  build-and-deploy:
    name: "Build, Push and Update"
    needs: terraform-base  # Wait for Job 1 to finish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Using your static GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # No manual 'aws ecr create' needed; Terraform Job 1 handled it
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./app
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      # - name: Terraform plan (Update image)
      #   # This final step tells ECS to pull the new image version
      #   run: terraform plan -auto-approve
     
      - name: Terraform Apply (Update Image)
        # This final step tells ECS to pull the new image version
        run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}"

        # --- SUCCESS NOTIFICATION ---
      - name: Slack Notification - Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: 'good'
          SLACK_MESSAGE: "✅ Deployment SUCCESSFUL! Your changes are live."
          SLACK_TITLE: "Deployment Status: SUCCESS"

      # --- FAILURE NOTIFICATION ---
      - name: Slack Notification - Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_COLOR: 'danger'
          SLACK_MESSAGE: "❌ Deployment FAILED. Check GitHub Actions logs."
          SLACK_TITLE: "Deployment Status: FAILED"